### ISSUE TITLE
JBDC connection string format

### ISSUE THREAD

**Issue by jpink** [shiveshnavin/firestore-jdbc-driver#13]
Hi,

if application allows only to specify JDBC connection string what will be the format for this driver?

I guess something like `jdbc:firebase:path/to/your/service-account.json`

That would be nice if it's documented in readme.

[JDBC URL Format For Different Databases](https://www.baeldung.com/java-jdbc-url-format)

**Comment by shiveshnavin** [comment]
@jpink Thanks for your input. Agreed, It will make more sense to follow the general format for defining the JDBC url. Given that the driver uses a path to file I have updated the format to `jdbc:firestore:file:/path/to/creds-file.json` with #14 in version `1.2.0`
